# Site settings
title: Headerlabs
email: premcarver@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Prem is testing for desc
baseurl: "https://www.headerlabs.com" # the subpath of your site, e.g. /blog/
url: "https://www.headerlabs.com/new" # the base hostname & protocol for your site

# User setting
owner: Headerlabs Co.
email: head@headerlabs.com
facebook_username: nowprem
twitter_username: premcarver
github_username: premcarver
address:
  - line: A111111
  - line: A22222
  # Feel free to add more lines here 
telephone: +++0982301803
copyright: headerlabs.com

# API settings
google_api_key: keyof google

# Build settings
markdown: kramdown